### ISSUE TITLE
[BE] - API cart trả về không đúng format

### ISSUE THREAD

**Issue by rubysky17** [ductandev/FE_hokkaidovietnam#41]
**Hiện trạng**
{
  "message": "Thành công !",
  "statusCode": 200,
  "content": [
    {
      "gio_hang_id": 16,
      "nguoi_dung_id": 3,
      "san_pham_id": 2,
      "so_luong": 4,
      "isDelete": false,
      "NguoiDung": {
        "nguoi_dung_id": 3,
        "vai_tro_id": 2,
        "ho_ten": "Mạnh Đạt",
        "email": "datvo@gmail.com",
        "mat_khau": "$2b$10$OtmKKsc9SgWdwV1oCUPJNuPvNYpbdBFn7LV8G5oMt8hm144R5gzfy",
        "dia_chi": "78 Hà Đông",
        "phuong_id": "27028",
        "quan_id": "767",
        "tinh_thanh_id": "79",
        "so_dien_thoai": "0987654321",
        "anh_dai_dien": "user.jpg",
        "gioi_tinh": "nam",
        "isDelete": false
      },
      "SanPham": {
        "san_pham_id": 2,
        "loai_san_pham_id": 1,
        "ten_san_pham": "Sữa chua vị quýt 200ml",
        "hinh_anh": [
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/dm9ohch92ekgfwlbkzlo.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917840/q2vdrjrffvw9ct0jbb3g.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/i3syhl2octvryaab4ifp.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/u9ocojbdpxktfulmwlof.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917824/vbzwbnbyajyiykl7a7xb.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/nof8obt2zpgrpmcnazkt.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/bwag5l0efylwdgnnshgz.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917823/gztt91ysk75zoyy9u6qv.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917823/ndegz9wmbyvhy6hvkhkp.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/ul7fko7mvkccpue33c1j.jpg",
          "http://res.cloudinary.com/dodirc71p/image/upload/v1714917822/hbuf6z6iwolpzwt4zkzv.jpg"
        ],
        "gia_ban": 50000,
        "gia_giam": 0,
        "mo_ta": "– Sữa chua vị quýt được chiết xuất từ đàn bò được chăn thả tự nhiên vùng Hokkaido và nước Quýt nội địa Nhật 100% Hokkaido là vùng đất có khí hậu mát mẻ, nguồn nước và không khí sạch cùng những thảo nguyên xanh tạo ra không gian chăn nuôi tự nhiên vô cùng lý tưởng cho bò sữa.\n– Môi trường sống ưu đãi của Hokkaido đã tạo ra hương vị sữa độc quyền nhờ luôn giữ nguyên độ tươi ngon như vừa mới vắt, cùng sắc thái thanh nhẹ.\n– Bí mật của sữa Hokkaido làm các bé say mê nằm ở con số 3.6. Theo số liệu của Hiệp hội Sữa Nhật Bản, con số 3.6 trong sữa thể hiện hàm lượng chất béo có trong sữa, cao hơn hẳn so với các loại sữa tươi thông thường.\n– Đặc biệt, công nghệ sát khuẩn sữa cực nhanh trong vòng 2s nên sữa Hokkaido vẫn giữ nguyên được các vi khuẩn có lợi cho hệ miễn dịch cho bé.\n",
        "thong_tin_chi_tiet": "– Sữa chua vị quýt được chiết xuất từ đàn bò được chăn thả tự nhiên vùng Hokkaido và nước Quýt nội địa Nhật 100% Hokkaido là vùng đất có khí hậu mát mẻ, nguồn nước và không khí sạch cùng những thảo nguyên xanh tạo ra không gian chăn nuôi tự nhiên vô cùng lý tưởng cho bò sữa.\n– Môi trường sống ưu đãi của Hokkaido đã tạo ra hương vị sữa độc quyền nhờ luôn giữ nguyên độ tươi ngon như vừa mới vắt, cùng sắc thái thanh nhẹ.\n– Bí mật của sữa Hokkaido làm các bé say mê nằm ở con số 3.6. Theo số liệu của Hiệp hội Sữa Nhật Bản, con số 3.6 trong sữa thể hiện hàm lượng chất béo có trong sữa, cao hơn hẳn so với các loại sữa tươi thông thường.\n– Đặc biệt, công nghệ sát khuẩn sữa cực nhanh trong vòng 2s nên sữa Hokkaido vẫn giữ nguyên được các vi khuẩn có lợi cho hệ miễn dịch cho bé.\n",
        "don_vi_tinh": null,
        "trang_thai_san_pham": true,
        "so_luong_trong_kho": 100,
        "san_pham_noi_bat": false,
        "san_pham_lien_quan": null,
        "isDelete": false
      }
    }
  ],
  "date": "2024-05-18T14:34:25.352Z"
}

**Mong muốn**
- trả về mảng gồm danh sách sản phẩm bỏ bớt những field dư thừa
- Chưa có trường số lượng bên trong giỏ hàng
- VD: [
- "message": "Thành công !",
  "statusCode": 200,
  "content": [
        {
              "san_pham_id": 2,
              "loai_san_pham_id": 1,
              "ten_san_pham": "Sữa chua vị quýt 200ml",
              "hinh_anh": [],
              "gia_ban": 50000,
              "gia_giam": 0,
              "mo_ta": "",
              "thong_tin_chi_tiet": "",
              "don_vi_tinh": null,
              "trang_thai_san_pham": true,
              "so_luong_trong_kho": 100,
              "san_pham_noi_bat": false,
              "san_pham_lien_quan": null,
              "so_luong": 30,
              "isDelete": false
            },
 {
              "san_pham_id": 2,
              "loai_san_pham_id": 1,
              "ten_san_pham": "Sữa chua vị quýt 200ml",
              "hinh_anh": [],
              "gia_ban": 50000,
              "gia_giam": 0,
              "mo_ta": "",
              "thong_tin_chi_tiet": "",
              "don_vi_tinh": null,
              "trang_thai_san_pham": true,
              "so_luong_trong_kho": 100,
              "san_pham_noi_bat": false,
              "san_pham_lien_quan": null,
              "so_luong": 30, 
              "isDelete": false
            },
  ],
  "date": "2024-05-18T14:34:25.352Z"]

**Comment by ductandev** [comment]
Fixed done response data requirement
